import { UserProfile, Sale } from '../types';

export interface DemoSupplier {
  id: string;
  name: string;
  contactName: string;
  phone: string;
  email: string;
  address: string;
  city: string;
  country: string;
  licenseNumber: string;
  licenseStatus: 'active' | 'pending' | 'expired';
  licenseExpiry: string;
  licenseAuthority: string;
  rating: number;
  onTimeDeliveryRate: number;
  qualityComplianceRate: number;
  leadTimeDays: number;
  pharmacyId: string;
  createdAt: number;
}

const NOW = Date.now();
const DAY = 24 * 60 * 60 * 1000;

// 1. COMPREHENSIVE ORGANIZATIONS & PEOPLE DATASET
export const DEMO_ALL_ORGANIZATIONS_AND_PEOPLE: Partial<UserProfile>[] = [
  // --- PHARMACIES & LICENSED PHARMACISTS ---
  {
    uid: 'demo_ph_addis_care',
    displayName: 'Addis Care Pharmacy',
    pharmacyName: 'Addis Care Pharmacy (Main Branch)',
    ownerName: 'Dr. Bereket Tadesse (Chief Pharmacist)',
    email: 'bereket.tadesse@addiscare.et',
    phone: '+251 91 123 4567',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Bole Medhanealem, Next to Edna Mall, Bole Sub-City',
    licenseNumber: 'EFDA-PH-2024-0412',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 180 * DAY,
    lastSubscriptionPaymentDate: NOW - 30 * DAY,
    createdAt: NOW - 180 * DAY,
    branchCount: 3,
    referralRewardMonthsEarned: 2,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_bole_family',
    displayName: 'Bole Family Pharmacy',
    pharmacyName: 'Bole Family Pharmacy & Wellness',
    ownerName: 'Pharm. Hanna Girma',
    email: 'hanna.girma@bolefamilyrx.com',
    phone: '+251 92 234 5678',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Bole Atlas Road, Behind Desalegn Hotel',
    licenseNumber: 'EFDA-PH-2024-0523',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 120 * DAY,
    lastSubscriptionPaymentDate: NOW - 25 * DAY,
    createdAt: NOW - 150 * DAY,
    branchCount: 2,
    referralRewardMonthsEarned: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_unity',
    displayName: 'Unity Pharmacy',
    pharmacyName: 'Unity Community Pharmacy',
    ownerName: 'Pharm. Yohannes Bekele',
    email: 'yohannes@unitypharmacy.et',
    phone: '+251 91 345 6789',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Kazanchis Commercial Avenue, Kirkos Sub-City',
    licenseNumber: 'EFDA-PH-2023-1109',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 90 * DAY,
    lastSubscriptionPaymentDate: NOW - 15 * DAY,
    createdAt: NOW - 160 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_hope_medical',
    displayName: 'Hope Medical Pharmacy',
    pharmacyName: 'Hope Medical Pharmacy & Clinical Dispensary',
    ownerName: 'Dr. Rahel Mengistu (Clinical Specialist)',
    email: 'rahel.m@hopemeds.et',
    phone: '+251 93 456 7890',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Piazza Churchill Avenue, Arada Sub-City',
    licenseNumber: 'EFDA-PH-2024-0718',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 210 * DAY,
    lastSubscriptionPaymentDate: NOW - 10 * DAY,
    createdAt: NOW - 200 * DAY,
    branchCount: 2,
    referralRewardMonthsEarned: 3,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_selam',
    displayName: 'Selam Pharmacy',
    pharmacyName: 'Selam Central Pharmacy',
    ownerName: 'Pharm. Dawit Haile',
    email: 'dawit.h@selamrx.et',
    phone: '+251 94 567 8901',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Megenagna Yeka Square, Near Zefmesh Grand Mall',
    licenseNumber: 'EFDA-PH-2023-0941',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 60 * DAY,
    lastSubscriptionPaymentDate: NOW - 20 * DAY,
    createdAt: NOW - 140 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_st_mary',
    displayName: 'St. Mary Pharmacy',
    pharmacyName: 'St. Mary Specialized Pharmacy',
    ownerName: 'Pharm. Almaz Bikila',
    email: 'almaz@stmarypharma.et',
    phone: '+251 91 678 9012',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Gotera Commercial Ring Road, Nifas Silk Lafto',
    licenseNumber: 'EFDA-PH-2024-0814',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 150 * DAY,
    lastSubscriptionPaymentDate: NOW - 18 * DAY,
    createdAt: NOW - 130 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_abyssinia_care',
    displayName: 'Abyssinia Care Pharmacy',
    pharmacyName: 'Abyssinia Health & Derma Pharmacy',
    ownerName: 'Pharm. Kenenisa Desta',
    email: 'kenenisa@abyssiniacare.et',
    phone: '+251 92 789 0123',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Merkato Military Tera Commercial Hub',
    licenseNumber: 'EFDA-PH-2023-0628',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 240 * DAY,
    lastSubscriptionPaymentDate: NOW - 5 * DAY,
    createdAt: NOW - 220 * DAY,
    branchCount: 2,
    referralRewardMonthsEarned: 2,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_apex_life',
    displayName: 'Apex Life Pharmacy',
    pharmacyName: 'Apex Life Regional Dispensary',
    ownerName: 'Pharm. Tigist Assefa',
    email: 'tigist.assefa@apexrxtoday.com',
    phone: '+251 91 890 1234',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Oromia',
    city: 'Adama',
    address: 'Posta Bet Kebele 03, Main Commercial Corridor',
    licenseNumber: 'EFDA-PH-2024-0311',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 110 * DAY,
    lastSubscriptionPaymentDate: NOW - 22 * DAY,
    createdAt: NOW - 110 * DAY,
    branchCount: 2,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_crown_meds',
    displayName: 'Crown Meds Pharmacy',
    pharmacyName: 'Crown Meds Adama Branch',
    ownerName: 'Dr. Solomon Ayana',
    email: 'solomon.a@crownmeds.et',
    phone: '+251 93 901 2345',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Oromia',
    city: 'Adama',
    address: 'Central Market Road, Adama City',
    licenseNumber: 'EFDA-PH-2023-1204',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 175 * DAY,
    lastSubscriptionPaymentDate: NOW - 8 * DAY,
    createdAt: NOW - 175 * DAY,
    branchCount: 1,
    referralRewardMonthsEarned: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_greencross_hawassa',
    displayName: 'GreenCross Pharmacy',
    pharmacyName: 'GreenCross Southern Hub Pharmacy',
    ownerName: 'Pharm. Helen Gashaw',
    email: 'helen.gashaw@greencross.et',
    phone: '+251 92 012 3456',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Sidama',
    city: 'Hawassa',
    address: 'Lake View Kebele 05, Near Regional Hospital',
    licenseNumber: 'EFDA-PH-2024-0198',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 200 * DAY,
    lastSubscriptionPaymentDate: NOW - 14 * DAY,
    createdAt: NOW - 190 * DAY,
    branchCount: 3,
    referralRewardMonthsEarned: 3,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_wellspring_hawassa',
    displayName: 'WellSpring Pharmacy',
    pharmacyName: 'WellSpring Family Care Pharmacy',
    ownerName: 'Pharm. Biniyam Fikre',
    email: 'biniyam.f@wellspringrx.et',
    phone: '+251 91 123 7890',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Sidama',
    city: 'Hawassa',
    address: 'Menaheria Commercial District, Hawassa',
    licenseNumber: 'EFDA-PH-2023-0855',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 85 * DAY,
    lastSubscriptionPaymentDate: NOW - 12 * DAY,
    createdAt: NOW - 95 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_horizon_bahirdar',
    displayName: 'Horizon Pharmacy',
    pharmacyName: 'Horizon Tana Health Pharmacy',
    ownerName: 'Dr. Mahlet Bogale',
    email: 'mahlet.b@horizonrx.et',
    phone: '+251 94 234 8901',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Amhara',
    city: 'Bahir Dar',
    address: 'Kebele 04 Lake Tana Avenue, Bahir Dar',
    licenseNumber: 'EFDA-PH-2024-0677',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 160 * DAY,
    lastSubscriptionPaymentDate: NOW - 19 * DAY,
    createdAt: NOW - 160 * DAY,
    branchCount: 2,
    referralRewardMonthsEarned: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_pioneer_bahirdar',
    displayName: 'Pioneer Pharmacy',
    pharmacyName: 'Pioneer Felege Hiwot Gate Pharmacy',
    ownerName: 'Pharm. Eskinder Alemayehu',
    email: 'eskinder.a@pioneerrx.et',
    phone: '+251 91 345 9012',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Amhara',
    city: 'Bahir Dar',
    address: 'Felege Hiwot Hospital Avenue, Bahir Dar',
    licenseNumber: 'EFDA-PH-2023-1022',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 45 * DAY,
    lastSubscriptionPaymentDate: NOW - 28 * DAY,
    createdAt: NOW - 120 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_beacon_gondar',
    displayName: 'Beacon Pharmacy',
    pharmacyName: 'Beacon Castle Square Pharmacy',
    ownerName: 'Pharm. Tsion Mengistu',
    email: 'tsion.m@beaconhealth.et',
    phone: '+251 92 456 0123',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Amhara',
    city: 'Gondar',
    address: 'Fasil Ghebbi Plaza, Gondar City',
    licenseNumber: 'EFDA-PH-2024-0489',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 130 * DAY,
    lastSubscriptionPaymentDate: NOW - 11 * DAY,
    createdAt: NOW - 100 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_serenity_diredawa',
    displayName: 'Serenity Pharmacy',
    pharmacyName: 'Serenity Free Trade Zone Pharmacy',
    ownerName: 'Pharm. Yared Tilahun',
    email: 'yared.t@serenityrx.et',
    phone: '+251 93 567 1234',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Dire Dawa',
    city: 'Dire Dawa',
    address: 'Kezira Commercial Boulevard, Dire Dawa',
    licenseNumber: 'EFDA-PH-2024-0234',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 195 * DAY,
    lastSubscriptionPaymentDate: NOW - 7 * DAY,
    createdAt: NOW - 180 * DAY,
    branchCount: 2,
    referralRewardMonthsEarned: 2,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_jimma_care',
    displayName: 'Jimma Central Pharmacy',
    pharmacyName: 'Jimma Central Medical Dispensary',
    ownerName: 'Dr. Meseret Worku',
    email: 'meseret.w@jimmacare.et',
    phone: '+251 91 678 2345',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Oromia',
    city: 'Jimma',
    address: 'Hermata Market Gate, Jimma Hospital Avenue',
    licenseNumber: 'EFDA-PH-2024-0112',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 70 * DAY,
    lastSubscriptionPaymentDate: NOW - 16 * DAY,
    createdAt: NOW - 110 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_bishoftu_lake',
    displayName: 'Bishoftu Lake Pharmacy',
    pharmacyName: 'Bishoftu Lake & Wellness Pharmacy',
    ownerName: 'Pharm. Daniel Habte',
    email: 'daniel.h@bishofturx.et',
    phone: '+251 92 789 3456',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Oromia',
    city: 'Bishoftu',
    address: 'Hora Lake Commercial Road, Bishoftu',
    licenseNumber: 'EFDA-PH-2023-0799',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'basic',
    subscriptionExpiryDate: NOW + 40 * DAY,
    lastSubscriptionPaymentDate: NOW - 26 * DAY,
    createdAt: NOW - 80 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_mekelle_peace',
    displayName: 'Mekelle Peace Pharmacy',
    pharmacyName: 'Mekelle Peace Community Pharmacy',
    ownerName: 'Pharm. Senait Kassa',
    email: 'senait.k@mekellerx.et',
    phone: '+251 94 890 4567',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Tigray',
    city: 'Mekelle',
    address: 'Romanat Square, Ayder Hospital Gate, Mekelle',
    licenseNumber: 'EFDA-PH-2024-0901',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 140 * DAY,
    lastSubscriptionPaymentDate: NOW - 9 * DAY,
    createdAt: NOW - 150 * DAY,
    branchCount: 2,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_dessie_hub',
    displayName: 'Dessie Central Pharmacy',
    pharmacyName: 'Dessie Central Rx Dispensary',
    ownerName: 'Pharm. Frehiwot Endale',
    email: 'frehiwot.e@dessierx.et',
    phone: '+251 91 901 5678',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Amhara',
    city: 'Dessie',
    address: 'Piazza Commercial District, Dessie City',
    licenseNumber: 'EFDA-PH-2023-1188',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'basic',
    subscriptionExpiryDate: NOW + 50 * DAY,
    lastSubscriptionPaymentDate: NOW - 20 * DAY,
    createdAt: NOW - 70 * DAY,
    branchCount: 1,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ph_kenema_flagship',
    displayName: 'Kenema Mega Pharmacy',
    pharmacyName: 'Kenema Mega Flagship Dispensary',
    ownerName: 'Dr. Tamrat Abebaw (Managing Pharmacist)',
    email: 'tamrat.abebaw@kenemarx.et',
    phone: '+251 93 012 6789',
    role: 'pharmacy',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Lideta Balcha Hospital Corridor, Addis Ababa',
    licenseNumber: 'EFDA-PH-2024-0045',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 270 * DAY,
    lastSubscriptionPaymentDate: NOW - 3 * DAY,
    createdAt: NOW - 240 * DAY,
    branchCount: 4,
    referralRewardMonthsEarned: 4,
    isFreeTrial: false,
  },

  // --- WHOLESALE PHARMACIES & IMPORTERS (ORGANIZATIONS & LEADERSHIP) ---
  {
    uid: 'demo_ws_ethiopha',
    displayName: 'Ethio-Pharma Wholesalers & Importers PLC',
    importerName: 'Ethio-Pharma Wholesalers & Importers PLC',
    ownerName: 'Yonas Mekonnen (Managing Director)',
    email: 'contact@demo-ethiopha.et',
    phone: '+251 11 667 8890',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Bole Sub-City Woreda 03, Logistics Zone, Addis Ababa',
    licenseNumber: 'EFDA-WHL-2023-0104',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 300 * DAY,
    lastSubscriptionPaymentDate: NOW - 15 * DAY,
    createdAt: NOW - 300 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ws_abyssinia',
    displayName: 'Abyssinia Medical Distributors',
    importerName: 'Abyssinia Medical Distributors & Wholesalers',
    ownerName: 'Senait Tadesse (VP Supply Chain)',
    email: 'orders@abyssiniamed.et',
    phone: '+251 11 442 3311',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Akaki Kality Industrial Zone, Cold Chain Terminal, Addis Ababa',
    licenseNumber: 'EFDA-WHL-2023-0219',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 250 * DAY,
    lastSubscriptionPaymentDate: NOW - 20 * DAY,
    createdAt: NOW - 260 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ws_redsea',
    displayName: 'Red Sea Pharmaceutical Importers',
    importerName: 'Red Sea Pharmaceutical Importers Ltd',
    ownerName: 'Tewodros Gebre (Director of Trade)',
    email: 'import@redseapharma.et',
    phone: '+251 25 111 8844',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Dire Dawa',
    city: 'Dire Dawa',
    address: 'Free Trade Logistics Gateway, Dire Dawa',
    licenseNumber: 'EFDA-WHL-2024-0088',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 220 * DAY,
    lastSubscriptionPaymentDate: NOW - 10 * DAY,
    createdAt: NOW - 210 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ws_crown_ea',
    displayName: 'Crown East Africa Healthcare Wholesales',
    importerName: 'Crown East Africa Healthcare Wholesales PLC',
    ownerName: 'Bethlehem Haile (Commercial Director)',
    email: 'sales@crowneastafrica.com',
    phone: '+251 11 553 9922',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Kirkos Industrial District, Meskel Flower Road',
    licenseNumber: 'EFDA-WHL-2024-0341',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 180 * DAY,
    lastSubscriptionPaymentDate: NOW - 25 * DAY,
    createdAt: NOW - 190 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ws_cadila_import',
    displayName: 'Cadila Pharma Importers & Wholesalers',
    importerName: 'Cadila Pharma Importers Ethiopia PLC',
    ownerName: 'Dawit Alemayehu (Chief Operating Officer)',
    email: 'supply@cadila-ethiopia.et',
    phone: '+251 11 661 0033',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Bole Cargo Logistics Center, Warehouse 4B',
    licenseNumber: 'EFDA-WHL-2023-0492',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 310 * DAY,
    lastSubscriptionPaymentDate: NOW - 12 * DAY,
    createdAt: NOW - 320 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ws_medtech_corp',
    displayName: 'MedTech Wholesale Pharma Hub',
    importerName: 'MedTech Wholesale Pharma Corporation',
    ownerName: 'Meron Tefera (Central Logistics Manager)',
    email: 'dispatch@medtechwholesales.et',
    phone: '+251 11 889 1234',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Nifas Silk Industrial Depot, Ring Road',
    licenseNumber: 'EFDA-WHL-2024-0155',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 140 * DAY,
    lastSubscriptionPaymentDate: NOW - 18 * DAY,
    createdAt: NOW - 150 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ws_buraq_imports',
    displayName: 'Buraq Medical Wholesalers',
    importerName: 'Buraq Medical Wholesalers & Consignments',
    ownerName: 'Daniel Habte (Trade Coordinator)',
    email: 'orders@buraqpharma.et',
    phone: '+251 25 112 5566',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Dire Dawa',
    city: 'Dire Dawa',
    address: 'Commercial Freight Depot, Dire Dawa',
    licenseNumber: 'EFDA-WHL-2024-0276',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 90 * DAY,
    lastSubscriptionPaymentDate: NOW - 14 * DAY,
    createdAt: NOW - 130 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ws_apex_supply',
    displayName: 'Apex Regional Wholesale Supplies',
    importerName: 'Apex Regional Healthcare Wholesales PLC',
    ownerName: 'Genet Wolde (Operations Head)',
    email: 'contact@apexsupplies.et',
    phone: '+251 22 111 9000',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Oromia',
    city: 'Adama',
    address: 'Expressway Interchange Logistics Park, Adama',
    licenseNumber: 'EFDA-WHL-2024-0418',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 200 * DAY,
    lastSubscriptionPaymentDate: NOW - 10 * DAY,
    createdAt: NOW - 170 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_ws_afro_asian',
    displayName: 'Afro-Asian Pharma Importers',
    importerName: 'Afro-Asian Pharmaceutical Importers Enterprise',
    ownerName: 'Mulugeta Kassa (Director of Regulatory Affairs)',
    email: 'regulatory@afroasianrx.et',
    phone: '+251 11 320 7744',
    role: 'importer',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Kolfe Keranio Sub-City, Commercial Depot 12',
    licenseNumber: 'EFDA-WHL-2023-0388',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 280 * DAY,
    lastSubscriptionPaymentDate: NOW - 22 * DAY,
    createdAt: NOW - 280 * DAY,
    isFreeTrial: false,
  },

  // --- MARKETING INTELLIGENCE TEAM MEMBERS (PEOPLE & CAMPAIGN LEADERS) ---
  {
    uid: 'demo_mkt_selam',
    displayName: 'Selamawit Teshome',
    name: 'Selamawit Teshome',
    email: 'selamawit.t@atech-marketing.et',
    phone: '+251 91 100 7701',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    address: 'ATECH HQ, Bole Commercial Plaza 5th Floor',
    shift: 'Full-time Standard',
    salary: 24000,
    commissionRate: 5,
    promoCode: 'SELAM2026',
    verificationStatus: 'approved',
    createdAt: NOW - 180 * DAY,
  },
  {
    uid: 'demo_mkt_samuel',
    displayName: 'Samuel Kebede',
    name: 'Samuel Kebede',
    email: 'samuel.k@atech-marketing.et',
    phone: '+251 91 200 7702',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    address: 'ATECH National Marketing Bureau, Addis Ababa',
    shift: 'Full-time Senior Lead',
    salary: 28000,
    commissionRate: 6,
    promoCode: 'SAMGROWTH',
    verificationStatus: 'approved',
    createdAt: NOW - 200 * DAY,
  },
  {
    uid: 'demo_mkt_kirubel',
    displayName: 'Kirubel Desta',
    name: 'Kirubel Desta',
    email: 'kirubel.d@atech-marketing.et',
    phone: '+251 91 300 7703',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Hawassa',
    address: 'Southern Regional Operations Desk, Hawassa',
    shift: 'Full-time Regional',
    salary: 19000,
    commissionRate: 5,
    promoCode: 'KIRUHEALTH',
    verificationStatus: 'approved',
    createdAt: NOW - 120 * DAY,
  },
  {
    uid: 'demo_mkt_eden',
    displayName: 'Eden Berhanu',
    name: 'Eden Berhanu',
    email: 'eden.b@atech-marketing.et',
    phone: '+251 91 400 7704',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Adama',
    address: 'Central Oromia Promotion Center, Adama',
    shift: 'Full-time Regional',
    salary: 20000,
    commissionRate: 5,
    promoCode: 'EDENPHARM',
    verificationStatus: 'approved',
    createdAt: NOW - 140 * DAY,
  },
  {
    uid: 'demo_mkt_bethelhem',
    displayName: 'Bethelhem Tefera',
    name: 'Bethelhem Tefera',
    email: 'bethelhem.t@atech-marketing.et',
    phone: '+251 91 500 7705',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Bahir Dar',
    address: 'Amhara Regional Hub, Lake Tana Commercial Desk',
    shift: 'Full-time Regional',
    salary: 19500,
    commissionRate: 5,
    promoCode: 'BETHCARE',
    verificationStatus: 'approved',
    createdAt: NOW - 110 * DAY,
  },
  {
    uid: 'demo_mkt_natnael',
    displayName: 'Natnael Desta',
    name: 'Natnael Desta',
    email: 'natnael.d@atech-marketing.et',
    phone: '+251 91 600 7706',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    address: 'Digital Pharmacy Growth Unit, Addis Ababa',
    shift: 'Full-time Standard',
    salary: 22000,
    commissionRate: 5,
    promoCode: 'NATIGROW',
    verificationStatus: 'approved',
    createdAt: NOW - 130 * DAY,
  },
  {
    uid: 'demo_mkt_meron',
    displayName: 'Meron Worku',
    name: 'Meron Worku',
    email: 'meron.w@atech-marketing.et',
    phone: '+251 91 700 7707',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Bishoftu',
    address: 'Corridor Campaign Center, Bishoftu',
    shift: 'Full-time Standard',
    salary: 18500,
    commissionRate: 4,
    promoCode: 'MERONRX',
    verificationStatus: 'approved',
    createdAt: NOW - 90 * DAY,
  },
  {
    uid: 'demo_mkt_elias',
    displayName: 'Elias Solomon',
    name: 'Elias Solomon',
    email: 'elias.s@atech-marketing.et',
    phone: '+251 91 800 7708',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Dire Dawa',
    address: 'Eastern Corridor Campaign Office, Dire Dawa',
    shift: 'Full-time Regional',
    salary: 19000,
    commissionRate: 5,
    promoCode: 'ELIASMARKET',
    verificationStatus: 'approved',
    createdAt: NOW - 105 * DAY,
  },
  {
    uid: 'demo_mkt_tsion',
    displayName: 'Tsion Mengistu',
    name: 'Tsion Mengistu',
    email: 'tsion.m@atech-marketing.et',
    phone: '+251 91 900 7709',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Jimma',
    address: 'Southwest Promotion Desk, Jimma',
    shift: 'Full-time Regional',
    salary: 18000,
    commissionRate: 4,
    promoCode: 'TSIONMED',
    verificationStatus: 'approved',
    createdAt: NOW - 80 * DAY,
  },
  {
    uid: 'demo_mkt_yared',
    displayName: 'Yared Tilahun',
    name: 'Yared Tilahun',
    email: 'yared.t@atech-marketing.et',
    phone: '+251 92 100 7710',
    role: 'marketing',
    country: 'Ethiopia',
    city: 'Gondar',
    address: 'Northern Heritage Area Desk, Gondar',
    shift: 'Full-time Regional',
    salary: 18500,
    commissionRate: 5,
    promoCode: 'YARED2026',
    verificationStatus: 'approved',
    createdAt: NOW - 95 * DAY,
  },

  // --- DISTRIBUTORS (REGIONAL DISTRIBUTION FLEET & HUBS) ---
  {
    uid: 'demo_dist_central',
    displayName: 'Central Addis Pharma Logistics Hub',
    distributorName: 'Central Addis Pharma Logistics Hub',
    ownerName: 'Abebe Bikila (Fleet Director)',
    email: 'dispatch@centraldist.et',
    phone: '+251 11 278 9900',
    role: 'distributor',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Kality Cold Storage Logistics Terminal, Depot 7',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 240 * DAY,
    lastSubscriptionPaymentDate: NOW - 15 * DAY,
    createdAt: NOW - 200 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_dist_rift_valley',
    displayName: 'Rift Valley Medical Distributors',
    distributorName: 'Rift Valley Medical Distributors PLC',
    ownerName: 'Kalkidan Lemma (Regional Lead)',
    email: 'info@riftvalleydist.et',
    phone: '+251 22 211 4455',
    role: 'distributor',
    country: 'Ethiopia',
    region: 'Oromia',
    city: 'Adama',
    address: 'Adama Industrial Expressway Gate 2',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 180 * DAY,
    lastSubscriptionPaymentDate: NOW - 20 * DAY,
    createdAt: NOW - 160 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_dist_north_corridor',
    displayName: 'Northern Corridor Distribution Hub',
    distributorName: 'Northern Corridor Distribution Hub',
    ownerName: 'Mulugeta Demisse (Managing Partner)',
    email: 'freight@northcorridor.et',
    phone: '+251 58 220 3344',
    role: 'distributor',
    country: 'Ethiopia',
    region: 'Amhara',
    city: 'Bahir Dar',
    address: 'Gish Abay Highway Depot, Bahir Dar',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 130 * DAY,
    lastSubscriptionPaymentDate: NOW - 12 * DAY,
    createdAt: NOW - 140 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_dist_eastern_gate',
    displayName: 'Eastern Gate Pharma Logistics',
    distributorName: 'Eastern Gate Pharma Logistics',
    ownerName: 'Nassir Ahmed (Operations Director)',
    email: 'logistics@easterngate.et',
    phone: '+251 25 111 6789',
    role: 'distributor',
    country: 'Ethiopia',
    region: 'Dire Dawa',
    city: 'Dire Dawa',
    address: 'Port Transit Gateway, Dire Dawa',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'premium',
    subscriptionExpiryDate: NOW + 210 * DAY,
    lastSubscriptionPaymentDate: NOW - 18 * DAY,
    createdAt: NOW - 170 * DAY,
    isFreeTrial: false,
  },
  {
    uid: 'demo_dist_southern_highlands',
    displayName: 'Southern Highlands Medical Dist.',
    distributorName: 'Southern Highlands Medical Distribution',
    ownerName: 'Tariku Shiferaw (Fleet Manager)',
    email: 'fleet@southerndist.et',
    phone: '+251 46 220 5511',
    role: 'distributor',
    country: 'Ethiopia',
    region: 'Sidama',
    city: 'Hawassa',
    address: 'Tabor Sub-City Logistics Center, Hawassa',
    verificationStatus: 'approved',
    subscriptionStatus: 'active',
    subscriptionType: 'standard',
    subscriptionExpiryDate: NOW + 150 * DAY,
    lastSubscriptionPaymentDate: NOW - 14 * DAY,
    createdAt: NOW - 120 * DAY,
    isFreeTrial: false,
  },

  // --- REGIONAL MANAGERS (TERRITORIAL COMPLIANCE & GROWTH LEADERS) ---
  {
    uid: 'demo_rm_almaz_kassa',
    displayName: 'Almaz Kassa',
    name: 'Almaz Kassa',
    email: 'almaz.kassa@atech-gov.et',
    phone: '+251 91 155 4433',
    role: 'regional_manager',
    country: 'Ethiopia',
    region: 'Addis Ababa',
    city: 'Addis Ababa',
    address: 'Regional Supervisory Bureau, Addis Ababa',
    verificationStatus: 'approved',
    createdAt: NOW - 250 * DAY,
  },
  {
    uid: 'demo_rm_dawit_haile',
    displayName: 'Dawit Haile',
    name: 'Dawit Haile',
    email: 'dawit.haile@atech-gov.et',
    phone: '+251 91 266 5544',
    role: 'regional_manager',
    country: 'Ethiopia',
    region: 'Oromia Region',
    city: 'Adama',
    address: 'Oromia Regional Coordination Office, Adama',
    verificationStatus: 'approved',
    createdAt: NOW - 220 * DAY,
  },
  {
    uid: 'demo_rm_hiwot_bikila',
    displayName: 'Hiwot Bikila',
    name: 'Hiwot Bikila',
    email: 'hiwot.bikila@atech-gov.et',
    phone: '+251 91 377 6655',
    role: 'regional_manager',
    country: 'Ethiopia',
    region: 'Amhara Region',
    city: 'Bahir Dar',
    address: 'Northern Supervisory Bureau, Bahir Dar',
    verificationStatus: 'approved',
    createdAt: NOW - 190 * DAY,
  },
  {
    uid: 'demo_rm_solomon_ayana',
    displayName: 'Solomon Ayana',
    name: 'Solomon Ayana',
    email: 'solomon.ayana@atech-gov.et',
    phone: '+251 91 488 7766',
    role: 'regional_manager',
    country: 'Ethiopia',
    region: 'Sidama',
    city: 'Hawassa',
    address: 'Southern Supervisory Hub, Hawassa',
    verificationStatus: 'approved',
    createdAt: NOW - 160 * DAY,
  },

  // --- SUPPORT DESK AGENTS ---
  {
    uid: 'demo_support_eskinder',
    displayName: 'Eskinder Alemayehu (Support Lead)',
    name: 'Eskinder Alemayehu',
    email: 'support.lead@atech-ops.et',
    phone: '+251 91 199 0011',
    role: 'support',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    verificationStatus: 'approved',
    createdAt: NOW - 200 * DAY,
  },
  {
    uid: 'demo_support_helen',
    displayName: 'Helen Gashaw (Billing Specialist)',
    name: 'Helen Gashaw',
    email: 'billing.desk@atech-ops.et',
    phone: '+251 91 299 0022',
    role: 'support',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    verificationStatus: 'approved',
    createdAt: NOW - 180 * DAY,
  }
];

// 2. CERTIFIED WHOLESALE SUPPLIERS DIRECTORY (FOR PHARMACY WHOLE SALES TAB)
export const DEMO_WHOLESALE_SUPPLIERS: DemoSupplier[] = [
  {
    id: 'supp_ethiopha_01',
    name: 'Ethio-Pharma Wholesalers & Importers PLC',
    contactName: 'Yonas Mekonnen (Logistics Director)',
    phone: '+251 11 667 8890',
    email: 'orders@demo-ethiopha.et',
    address: 'Bole Sub-City Woreda 03, Logistics Zone',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2023/0104',
    licenseStatus: 'active',
    licenseExpiry: '2026-12-31',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 5.0,
    onTimeDeliveryRate: 98,
    qualityComplianceRate: 99,
    leadTimeDays: 2,
    pharmacyId: 'demo_ph_addis_care',
    createdAt: NOW - 120 * DAY,
  },
  {
    id: 'supp_abyssinia_02',
    name: 'Abyssinia Medical Distributors',
    contactName: 'Senait Tadesse (Head of Distribution)',
    phone: '+251 11 442 3311',
    email: 'orders@abyssiniamed.et',
    address: 'Akaki Kality Industrial Zone, Cold Chain Depot',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2023/0219',
    licenseStatus: 'active',
    licenseExpiry: '2027-04-15',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.9,
    onTimeDeliveryRate: 96,
    qualityComplianceRate: 99,
    leadTimeDays: 3,
    pharmacyId: 'demo_ph_bole_family',
    createdAt: NOW - 110 * DAY,
  },
  {
    id: 'supp_redsea_03',
    name: 'Red Sea Pharmaceutical Importers Ltd',
    contactName: 'Tewodros Gebre (Trade Manager)',
    phone: '+251 25 111 8844',
    email: 'trade@redseapharma.et',
    address: 'Free Trade Logistics Gateway, Kezira',
    city: 'Dire Dawa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2024/0088',
    licenseStatus: 'active',
    licenseExpiry: '2026-11-20',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.8,
    onTimeDeliveryRate: 94,
    qualityComplianceRate: 98,
    leadTimeDays: 4,
    pharmacyId: 'demo_ph_serenity_diredawa',
    createdAt: NOW - 95 * DAY,
  },
  {
    id: 'supp_crown_ea_04',
    name: 'Crown East Africa Healthcare Wholesales',
    contactName: 'Bethlehem Haile (Commercial Lead)',
    phone: '+251 11 553 9922',
    email: 'sales@crowneastafrica.com',
    address: 'Meskel Flower Commercial District, Kirkos',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2024/0341',
    licenseStatus: 'active',
    licenseExpiry: '2027-02-28',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.9,
    onTimeDeliveryRate: 97,
    qualityComplianceRate: 100,
    leadTimeDays: 2,
    pharmacyId: 'demo_ph_unity',
    createdAt: NOW - 85 * DAY,
  },
  {
    id: 'supp_cadila_05',
    name: 'Cadila Pharma Importers Ethiopia PLC',
    contactName: 'Dawit Alemayehu (Operations Chief)',
    phone: '+251 11 661 0033',
    email: 'supply@cadila-ethiopia.et',
    address: 'Bole Cargo Logistics Center, Warehouse 4B',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2023/0492',
    licenseStatus: 'active',
    licenseExpiry: '2026-10-31',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 5.0,
    onTimeDeliveryRate: 99,
    qualityComplianceRate: 100,
    leadTimeDays: 2,
    pharmacyId: 'demo_ph_hope_medical',
    createdAt: NOW - 130 * DAY,
  },
  {
    id: 'supp_medtech_06',
    name: 'MedTech Wholesale Pharma Corporation',
    contactName: 'Meron Tefera (Distribution Lead)',
    phone: '+251 11 889 1234',
    email: 'dispatch@medtechwholesales.et',
    address: 'Nifas Silk Industrial Ring Road Depot',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2024/0155',
    licenseStatus: 'active',
    licenseExpiry: '2027-01-15',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.8,
    onTimeDeliveryRate: 95,
    qualityComplianceRate: 98,
    leadTimeDays: 3,
    pharmacyId: 'demo_ph_selam',
    createdAt: NOW - 75 * DAY,
  },
  {
    id: 'supp_buraq_07',
    name: 'Buraq Medical Wholesalers & Consignments',
    contactName: 'Daniel Habte (Trade Coordinator)',
    phone: '+251 25 112 5566',
    email: 'orders@buraqpharma.et',
    address: 'Commercial Freight Depot 8, Kezira',
    city: 'Dire Dawa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2024/0276',
    licenseStatus: 'active',
    licenseExpiry: '2026-08-30',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.7,
    onTimeDeliveryRate: 92,
    qualityComplianceRate: 97,
    leadTimeDays: 4,
    pharmacyId: 'demo_ph_serenity_diredawa',
    createdAt: NOW - 60 * DAY,
  },
  {
    id: 'supp_apex_08',
    name: 'Apex Regional Healthcare Wholesales PLC',
    contactName: 'Genet Wolde (Adama Logistics Manager)',
    phone: '+251 22 111 9000',
    email: 'contact@apexsupplies.et',
    address: 'Expressway Interchange Logistics Park',
    city: 'Adama',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2024/0418',
    licenseStatus: 'active',
    licenseExpiry: '2026-09-18',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.9,
    onTimeDeliveryRate: 97,
    qualityComplianceRate: 99,
    leadTimeDays: 2,
    pharmacyId: 'demo_ph_apex_life',
    createdAt: NOW - 90 * DAY,
  },
  {
    id: 'supp_greencross_dist_09',
    name: 'GreenCross Southern Wholesales & Supply',
    contactName: 'Helen Gashaw (Operations Director)',
    phone: '+251 46 220 8899',
    email: 'supply@greencrosswholesales.et',
    address: 'Lake View Kebele 05 Commercial Zone',
    city: 'Hawassa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2024/0512',
    licenseStatus: 'active',
    licenseExpiry: '2027-05-30',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.9,
    onTimeDeliveryRate: 96,
    qualityComplianceRate: 99,
    leadTimeDays: 3,
    pharmacyId: 'demo_ph_greencross_hawassa',
    createdAt: NOW - 65 * DAY,
  },
  {
    id: 'supp_tana_pharma_10',
    name: 'Lake Tana Medical Wholesale Supplies',
    contactName: 'Mahlet Bogale (Regional Lead)',
    phone: '+251 58 226 7788',
    email: 'orders@tanapharma.et',
    address: 'Felege Hiwot Commercial Corridor',
    city: 'Bahir Dar',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2023/0890',
    licenseStatus: 'active',
    licenseExpiry: '2026-11-15',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.8,
    onTimeDeliveryRate: 95,
    qualityComplianceRate: 98,
    leadTimeDays: 3,
    pharmacyId: 'demo_ph_horizon_bahirdar',
    createdAt: NOW - 80 * DAY,
  },
  {
    id: 'supp_afro_asian_11',
    name: 'Afro-Asian Pharmaceutical Importers',
    contactName: 'Mulugeta Kassa (Director of Regulatory)',
    phone: '+251 11 320 7744',
    email: 'regulatory@afroasianrx.et',
    address: 'Kolfe Keranio Depot 12, Ring Road',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2023/0388',
    licenseStatus: 'active',
    licenseExpiry: '2026-12-15',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 5.0,
    onTimeDeliveryRate: 99,
    qualityComplianceRate: 100,
    leadTimeDays: 2,
    pharmacyId: 'demo_ph_abyssinia_care',
    createdAt: NOW - 100 * DAY,
  },
  {
    id: 'supp_jimma_dist_12',
    name: 'Southwest Regional Medical Wholesalers',
    contactName: 'Dr. Meseret Worku (Operations Lead)',
    phone: '+251 47 111 4455',
    email: 'orders@southwestpharma.et',
    address: 'Hospital Avenue Commercial Gate 3',
    city: 'Jimma',
    country: 'Ethiopia',
    licenseNumber: 'EFDA/WHL-2024/0622',
    licenseStatus: 'active',
    licenseExpiry: '2027-03-20',
    licenseAuthority: 'EFDA - Ethiopian Food & Drug Authority',
    rating: 4.8,
    onTimeDeliveryRate: 94,
    qualityComplianceRate: 98,
    leadTimeDays: 4,
    pharmacyId: 'demo_ph_jimma_care',
    createdAt: NOW - 50 * DAY,
  }
];

// 3. CLINICAL-GRADE MEDICINE MASTER CATALOG DEFINITION
export interface MedicineCatalogItem {
  productName: string;
  genericName: string;
  category: string;
  unitPrice: number;
  countryOfOrigin: string;
  dispensingUnit: string;
}

export const DEMO_MEDICINE_CATALOG: MedicineCatalogItem[] = [
  { productName: 'Paracetamol 500mg Tablets', genericName: 'Paracetamol', category: 'Analgesics & Antipyretics', unitPrice: 18.5, countryOfOrigin: 'Ethiopia (Cadila)', dispensingUnit: 'Box of 100' },
  { productName: 'Amoxicillin 500mg Capsules', genericName: 'Amoxicillin', category: 'Antibiotics & Anti-infectives', unitPrice: 29.0, countryOfOrigin: 'Ethiopia (EPHARM)', dispensingUnit: 'Pack of 100' },
  { productName: 'Omeprazole 20mg Delayed-Release', genericName: 'Omeprazole', category: 'Gastrointestinal', unitPrice: 28.5, countryOfOrigin: 'India', dispensingUnit: 'Box of 28' },
  { productName: 'Metformin 500mg Extended-Release', genericName: 'Metformin HCl', category: 'Cardiovascular & Antidiabetic', unitPrice: 27.2, countryOfOrigin: 'India', dispensingUnit: 'Box of 100' },
  { productName: 'Ciprofloxacin 500mg Tablets', genericName: 'Ciprofloxacin', category: 'Antibiotics & Anti-infectives', unitPrice: 32.5, countryOfOrigin: 'Germany', dispensingUnit: 'Box of 10' },
  { productName: 'Azithromycin 500mg Tablets', genericName: 'Azithromycin', category: 'Antibiotics & Anti-infectives', unitPrice: 55.0, countryOfOrigin: 'India', dispensingUnit: 'Box of 3' },
  { productName: 'Vitamin C 500mg Chewable', genericName: 'Ascorbic Acid', category: 'Vitamins & Minerals', unitPrice: 22.8, countryOfOrigin: 'Ethiopia (Julphar)', dispensingUnit: 'Bottle of 60' },
  { productName: 'Multivitamin + Zinc Synergy', genericName: 'Multivitamin Formula', category: 'Vitamins & Minerals', unitPrice: 42.0, countryOfOrigin: 'Switzerland', dispensingUnit: 'Bottle of 30' },
  { productName: 'Artemether + Lumefantrine (Coartem)', genericName: 'Artemether / Lumefantrine', category: 'Antimalarial', unitPrice: 75.0, countryOfOrigin: 'Switzerland (Novartis)', dispensingUnit: 'Pack of 24' },
  { productName: 'Diclofenac Sodium 50mg Tablets', genericName: 'Diclofenac Sodium', category: 'Analgesics & Anti-inflammatory', unitPrice: 24.5, countryOfOrigin: 'Cyprus', dispensingUnit: 'Box of 20' },
  { productName: 'Cetirizine 10mg Tablets', genericName: 'Cetirizine HCl', category: 'Respiratory & Allergy', unitPrice: 19.5, countryOfOrigin: 'India', dispensingUnit: 'Box of 30' },
  { productName: 'Salbutamol 100mcg Inhaler', genericName: 'Salbutamol Sulfate', category: 'Respiratory & Allergy', unitPrice: 88.0, countryOfOrigin: 'United Kingdom (GSK)', dispensingUnit: 'Canister (200 Doses)' },
  { productName: 'Atorvastatin 20mg Tablets', genericName: 'Atorvastatin Calcium', category: 'Cardiovascular & Antidiabetic', unitPrice: 48.0, countryOfOrigin: 'India', dispensingUnit: 'Box of 30' },
  { productName: 'Amlodipine 5mg Tablets', genericName: 'Amlodipine Besylate', category: 'Cardiovascular & Antidiabetic', unitPrice: 26.0, countryOfOrigin: 'India', dispensingUnit: 'Box of 30' },
  { productName: 'Ibuprofen 400mg Tablets', genericName: 'Ibuprofen', category: 'Analgesics & Anti-inflammatory', unitPrice: 21.0, countryOfOrigin: 'Ethiopia (EPHARM)', dispensingUnit: 'Box of 100' },
  { productName: 'Gentamicin 80mg/2ml Injection', genericName: 'Gentamicin Sulfate', category: 'Antibiotics & Anti-infectives', unitPrice: 38.0, countryOfOrigin: 'Germany', dispensingUnit: 'Pack of 5 Ampoules' },
  { productName: 'Pantoprazole 40mg Tablets', genericName: 'Pantoprazole Sodium', category: 'Gastrointestinal', unitPrice: 35.0, countryOfOrigin: 'India', dispensingUnit: 'Box of 28' },
  { productName: 'Ceftriaxone 1g Injection Vial', genericName: 'Ceftriaxone Sodium', category: 'Antibiotics & Anti-infectives', unitPrice: 65.0, countryOfOrigin: 'India', dispensingUnit: 'Single Vial + Water' },
  { productName: 'Enalapril 10mg Tablets', genericName: 'Enalapril Maleate', category: 'Cardiovascular & Antidiabetic', unitPrice: 23.5, countryOfOrigin: 'India', dispensingUnit: 'Box of 30' },
  { productName: 'Oral Rehydration Salts (ORS)', genericName: 'WHO-Formula ORS', category: 'Gastrointestinal', unitPrice: 12.0, countryOfOrigin: 'Ethiopia', dispensingUnit: 'Box of 10 Sachets' },
  { productName: 'Doxycycline 100mg Capsules', genericName: 'Doxycycline Hyclate', category: 'Antibiotics & Anti-infectives', unitPrice: 28.0, countryOfOrigin: 'India', dispensingUnit: 'Box of 10' },
  { productName: 'Hydrocortisone 1% Topical Cream', genericName: 'Hydrocortisone', category: 'Dermatology', unitPrice: 34.0, countryOfOrigin: 'United Kingdom', dispensingUnit: 'Tube 15g' },
  { productName: 'Metronidazole 400mg Tablets', genericName: 'Metronidazole', category: 'Gastrointestinal', unitPrice: 22.0, countryOfOrigin: 'Ethiopia (Cadila)', dispensingUnit: 'Box of 100' },
  { productName: 'Clotrimazole 1% Cream', genericName: 'Clotrimazole', category: 'Dermatology', unitPrice: 29.5, countryOfOrigin: 'Germany (Bayer)', dispensingUnit: 'Tube 20g' }
];

export const DEMO_MEDICINE_METADATA_MAP: Record<string, { category: string; genericName: string; countryOfOrigin: string }> = {};
DEMO_MEDICINE_CATALOG.forEach(m => {
  DEMO_MEDICINE_METADATA_MAP[m.productName.toLowerCase().trim()] = {
    category: m.category,
    genericName: m.genericName,
    countryOfOrigin: m.countryOfOrigin
  };
});

// 4. RICH NETWORK MARKET INTELLIGENCE SALES TRANSACTIONS
export function generateDemoMarketSales(): Sale[] {
  const sales: Sale[] = [];
  const pharmacies = DEMO_ALL_ORGANIZATIONS_AND_PEOPLE.filter(u => u.role === 'pharmacy');
  let saleIdCounter = 1;

  // Generate sales across the last 30 days
  for (let dayOffset = 30; dayOffset >= 0; dayOffset--) {
    const dayTimestamp = NOW - dayOffset * DAY;
    
    // Number of transactions on this day (between 8 and 18)
    const txnsToday = 10 + ((dayOffset * 7) % 8);
    
    for (let t = 0; t < txnsToday; t++) {
      const pIdx = (dayOffset * 3 + t * 5) % pharmacies.length;
      const pharmacy = pharmacies[pIdx];
      const pId = pharmacy.uid || `pharm_${pIdx}`;
      const pName = pharmacy.pharmacyName || pharmacy.displayName || 'Network Pharmacy';
      
      // Select 1 to 4 items for this transaction
      const itemCount = 1 + ((dayOffset + t) % 3);
      const items: any[] = [];
      let saleTotal = 0;
      
      for (let i = 0; i < itemCount; i++) {
        const medIdx = (dayOffset * 2 + t * 4 + i * 3) % DEMO_MEDICINE_CATALOG.length;
        const med = DEMO_MEDICINE_CATALOG[medIdx];
        
        // Quantity multiplier: common items sell 10 to 60 units per order
        const baseQty = med.category.includes('Analgesics') ? 35 :
                        med.category.includes('Antibiotics') ? 22 :
                        med.category.includes('Gastrointestinal') ? 18 : 12;
        const quantity = baseQty + ((t * 3 + i) % 15);
        const itemTotal = quantity * med.unitPrice;
        
        items.push({
          productId: `prod_${medIdx}`,
          name: med.productName,
          quantity,
          price: med.unitPrice,
          total: itemTotal,
          category: med.category
        });
        saleTotal += itemTotal;
      }
      
      sales.push({
        id: `demo_sale_${String(saleIdCounter).padStart(5, '0')}`,
        pharmacyId: pId,
        pharmacyName: pName,
        total: Math.round(saleTotal * 100) / 100,
        subtotal: Math.round(saleTotal * 100) / 100,
        tax: 0,
        discount: 0,
        paymentMethod: (dayOffset + t) % 2 === 0 ? 'cash' : 'credit',
        items,
        createdAt: dayTimestamp + (t * 45 * 60 * 1000),
        status: 'completed'
      } as any);
      
      saleIdCounter++;
    }
  }

  return sales;
}

export const DEMO_MARKET_SALES: Sale[] = generateDemoMarketSales();
